### ISSUE TITLE
[기타]  새 계정 만든 후 push 할 때 fatal: unable to access  오류 해결

### ISSUE THREAD

**Issue by Jason-time** [Cat-Hanbit/README#43]
![image](https://user-images.githubusercontent.com/65810251/82814357-f68cd680-9ed1-11ea-9a46-b9c44c69d8b2.png)

예전 로그인 설정이 그대로 남아 있어서 오류가 나오는 경우, 
기존의 깃헙 정보를 제어판 - 자격 증명 관리자에서 삭제합니다. 

그림을 참조하세요. 
삭제하고 다시  git push 명령어를 누르면   깃헙 로그인 화면이 나오고 새로 만든 계정 암호를 넣어서 로그인하면  정상 작동합니다.  그 이후 git push 를 하면 잘 작동합니다.

**Comment by yeslee-v** [comment]
안녕하세요, 그렇게 했는데도 안되는 이유는 뭘까요? git remote rm 또한 실행해보았는데 결과는 같습니다..
