### ISSUE TITLE
[질문 | GitHub에 생성된 repository를 delete하는 방법이 있나요? (본문 없음) 

### ISSUE THREAD

**Issue by ghost** [Cat-Hanbit/README#52]
## 사전 체크리스트
- [ ] 나와 비슷한 질문이 있는지 먼저 검색을 해보았다 ([닫힌 이슈](https://github.com/Cat-Hanbit/README/issues?q=is%3Aissue+is%3Aclosed) 포함)
- [ ] 적절한 Label을 달았다(e.g. 4장 / 오류 / 질문 등)

## 어떤 유형의 이슈인가요?
[책 질문 | 오탈자 제보 | 오류 정정 요청 | 기타]

## 본문의 위치는 어디인가요?
최대한 정확하게 작성해 주세요(e.g. 4장 1절, 142페이지)

## 실습 환경을 알려주세요
(e.g. Windows 10, Mac 카탈리나 10.15.1, SourceTree 4.0)

## 세부 내용
질문의 내용을 자세하게 작성해 주세요.
실습 당시의 상황을 스크린 샷등을 이용해 첨부해 주시면 더욱 좋습니다(내 컴퓨터의 이미지를 첨부하고 싶은 위치로 드래그 앤 드롭을 하면 이슈 페이지에 업로드하고 이미지를 삽입할 수 있습니다).

**Comment by honux77** [comment]
깃헙 저장소 설정 (https://github.com/내아이디/저장소주소/settings) 에서 제일 아래 삭제하는 메뉴를 선택하면 삭제할 수 있습니다.
