### ISSUE TITLE
[질문] p.23 - 로그인 실패

### ISSUE THREAD

**Issue by hyeonji21** [Cat-Hanbit/README#59]
chapter- 3장 p.23
git push origin master를 통해 원격저장소에 올리려고 했지만, 로그인창이 뜨지 않고 연결이 계속 되지 않아서 학습을 진행할 수 없는 상황입니다. 답변해주시면 감사하겠습니다ㅠ

**Comment by hyeonji21** [comment]
해결 완료.

**Comment by kjin0204** [comment]
어떻게 해결되었나요?
