### ISSUE TITLE
[질문] 4장 p.171 rebase 관련 질문.

### ISSUE THREAD

**Issue by guswns1659** [Cat-Hanbit/README#6]
## 본문의 위치는 어디인가요?
4장 3절 171페이지

## 실습 환경을 알려주세요
Linux Ubuntu 18.04, Linux terminal

## 세부 내용
p.171 상단의 "리베이스를 하려면 다른 개발자가 이 변경사항을 사용하고 있지 않아야 한다는 말입니다.~~"의 내용이 제가 이해한 것이 맞을까요? 

원격저장소의 커밋을 rebase할 경우 다른 개발자는 rebase의 내용을 정확히 모르기 때문에 버전 관리에 혼선이 올 수 있다는 의미로 생각했습니다!  
![Git rebase질문_p 171](https://user-images.githubusercontent.com/55608425/74506847-12c9c080-4f3e-11ea-8ae1-f7032dcbfad6.jpg)

**Comment by honux77** [comment]
`결과를 모를 수 있기 때문에` 란 설명도 맞습니다. 
원인은 리베이스하면 원본 커밋들과 다른 커밋들이 생성되기 때문이구요.
1) 내 커밋들을 원격에 푸시한다.
2) 팀원들이 크 커밋 위해 다른 커밋을 생성한다.
3) 커밋들을 리베이스한다.
4) 다시 푸시한다.

1) ~ 4)까지의 결과로 원격 저장소에는 내용은 같지만 서로 다른 것으로 간주되는 (체크섬이 다른) 커밋이 존재하게 됩니다. 그리고 누군가는 이를 리베이스하고 머지하고 반복하는 동안 매우 지저분하고 복잡한 히스토리를 가지게 될 가능성이 높습니다. 당연히 충돌도 더 자주 생기고 관리도 어려워지게 됩니다.

**Comment by guswns1659** [comment]
네! 이해했습니다. 자세한 설명 감사합니다.
