### ISSUE TITLE
[오탈자 제보 ] 목차 오타

### ISSUE THREAD

**Issue by roslein** [Cat-Hanbit/README#61]
## 사전 체크리스트
- [x] 나와 비슷한 질문이 있는지 먼저 검색을 해보았다 ([닫힌 이슈](https://github.com/Cat-Hanbit/README/issues?q=is%3Aissue+is%3Aclosed) 포함)네
- [x] 적절한 Label을 달았다(e.g. 4장 / 오류 / 질문 등)

## 어떤 유형의 이슈인가요?
[오탈자 제보 ]

## 본문의 위치는 어디인가요?
최대한 정확하게 작성해 주세요(e.g. 4장 1절, 142페이지)

목차 chapter 0의 01아래 02여야 하는데 03으로 되어있음.

**Comment by milooy** [comment]
어라! 감사합니다 ㅎㅎ 다음 인쇄때 반영하겠습니다
