### ISSUE TITLE
[질문 ] p.23 git push 오류

### ISSUE THREAD

**Issue by jinnchoi** [Cat-Hanbit/README#63]
## 사전 체크리스트
- [v] 나와 비슷한 질문이 있는지 먼저 검색을 해보았다 ([닫힌 이슈](https://github.com/Cat-Hanbit/README/issues?q=is%3Aissue+is%3Aclosed) 포함)
- [ ] 적절한 Label을 달았다(e.g. 4장 / 오류 / 질문 등)

## 어떤 유형의 이슈인가요?
[책 질문 | 오탈자 제보 | 오류 정정 요청 | 기타]
책질문
## 본문의 위치는 어디인가요?
최대한 정확하게 작성해 주세요(e.g. 4장 1절, 142페이지)
0장 p.23
## 실습 환경을 알려주세요
(e.g. Windows 10, Mac 카탈리나 10.15.1, SourceTree 4.0)
windows 10
## 세부 내용
질문의 내용을 자세하게 작성해 주세요.
실습 당시의 상황을 스크린 샷등을 이용해 첨부해 주시면 더욱 좋습니다(내 컴퓨터의 이미지를 첨부하고 싶은 위치로 드래그 앤 드롭을 하면 이슈 페이지에 업로드하고 이미지를 삽입할 수 있습니다).
git push origin master를 입력하면 커서만 나오고 그 뒤로 동작이 되지 않습니다.
closed된 질문들도 찾아봤는데요. 자체적으로 해결했다고 답만 올라와 있네요.
그래서 x누르고 나가려고 하면 process are running in session 이런 창이 또 나와요.ㅠㅠ
![git push](https://user-images.githubusercontent.com/85519454/121758647-3c5c2180-cb5d-11eb-857c-3156618eb3e1.jpg)
![에러](https://user-images.githubusercontent.com/85519454/121758651-41b96c00-cb5d-11eb-951b-3193b59fe343.jpg)

**Comment by jinnchoi** [comment]
폴더와 git의 repository name을 같게 해주니까 되네요 ㅎㅎㅎ 해결하는데 시간이 좀 걸렸어요

**Comment by irishNoah** [comment]
저도 여기서 계속 막히던데 폴더와 git의 repository name도 님처럼 같게 해줬는데 저는 안되거든요? 구체적으로 어떻게 하신 것인지 말씀 좀 해주실 수 있을까요???

**Comment by jinnchoi** [comment]
1. 이미 작성된 txt 문서의 내용을 바꿔서 저장한 다음 git add README.txt를 했는지 확인한다.(git commit -m "사이트설명" 해놓으면 좋음)
2. git push origin master를 해본다. 이때 바로 위에 폴더명 옆에 (master)대신 (main)이라고 되어 있으면 git push origin main을 해본다.
3. 안되고 영어가 막 나오면서 git pull이라고 되어있으면 git pull origin main 을 해본다.
4. 다시 git push origin main을 한다.
--저는 repository name 같게 해주고 위에 처럼하니까 되더라구요.-- ^^ 
혹시 이래도 안되시면, 해당 화면을 캡쳐해서 보여주세요^^

**Comment by pachomiuses** [comment]
![cc](https://user-images.githubusercontent.com/46921199/123300317-706c1500-d555-11eb-9e50-5b7d285239cb.jpg)
같게 해줘도 안되는데 혹시 방법 아시나요?
