### ISSUE TITLE
[질문] 171p 강제푸시기능

### ISSUE THREAD

**Issue by richard-kim7** [Cat-Hanbit/README#81]
## 사전 체크리스트
- [ ] 나와 비슷한 질문이 있는지 먼저 검색을 해보았다 ([닫힌 이슈](https://github.com/Cat-Hanbit/README/issues?q=is%3Aissue+is%3Aclosed) 포함)
- [ ] 적절한 Label을 달았다(e.g. 4장 / 오류 / 질문 등)

## 어떤 유형의 이슈인가요?
[책 질문 | 오탈자 제보 | 오류 정정 요청 | 기타]

## 본문의 위치는 어디인가요?
171페이지~172페이지 강제푸시 부분(e.g. 4장 1절, 142페이지)

## 실습 환경을 알려주세요
(e.g. Windows 11, SourceTree 버전 모름)

## 세부 내용
171 강제푸시 진행하는데 다음과 같은 에러가 납니다.
![화면 캡처 2022-12-29 115227](https://user-images.githubusercontent.com/119490107/209897469-86be12eb-41fa-4e5c-9214-e0cdf1b907a9.png)

## 기타
처음 게시판(?)에 접속을 해서 내용확인도 하고 질문도 하는데 git을 잘 몰라서 공부하려고 책을 샀는데 질문게시판을 이렇게 github로 해 놓으시니 적응하는데 도움이 될지는 잘 몰라도 상당히 불편하군요. 검색하기도 불편하고 글 올리는것도 불편합니다. 질문/답변 게시판은 일반 카페 등의 게시판으로 옮기실 생각은 없으신지요? 사용자 입장의 게시판이 아니고 운영자 입장의 게시판 운영이라 생각됩니다. 공부하기도 힘든데 질문하는데까지 신경을 좀 덜 썼으면 하는 바램이 학습하는 사람의 입장에서는 생깁니다.

**Comment by honux77** [comment]
늦었지만 의견 감사합니다. 고민해 보고 QA 게시판을 옮기는 방안 검토해 보겠습니다.
